[package]
name = "haven_authoring"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
haven_identity = { path = "../haven_identity" }
haven_assets = { path = "../haven_assets" }
haven_core = { path = "../haven_core" }
haven_world = { path = "../haven_world" }
serde.workspace = true
serde_json.workspace = true
