#!/usr/bin/env python3
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'content/worldgen/scenes/world_asset_acceptance/world_visual_w52_acceptance_scene_v1.json'
W,H=64,40
terrain=[['grass' for _ in range(W)] for _ in range(H)]
# interior floor pad
for y in range(8,29):
 for x in range(5,58): terrain[y][x]='wood_floor'
objects=[
 {'id':'w52_bar_counter','assetId':'furniture_bar_counter_wood_4','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[8,12,4,1],'collisionRect':[8,12,4,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_bar','kind':'inspect','rect':[8,11,4,2]}]},
 {'id':'w52_barrel','assetId':'container_barrel_wood_01','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[18,11,1,2],'collisionRect':[18,12,1,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_barrel','kind':'inspect','rect':[18,12,1,1]}]},
 {'id':'w52_keg','assetId':'container_keg_wood_01','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[22,11,1,2],'collisionRect':[22,12,1,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_keg','kind':'inspect','rect':[22,12,1,1]}]},
 {'id':'w52_hearth_lit','assetId':'fixture_fireplace_cast_iron_01','state':'lit','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[28,12,1,1],'collisionRect':[28,12,1,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_hearth','kind':'inspect','rect':[28,12,1,1]}]},
 {'id':'w52_cave_mouth','assetId':'cave_entrance_default','state':'open','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[36,10,1,3],'collisionRect':[36,12,0,0],'layer':'high_object','blocksMovement':False,'occludesPlayer':True,'fadeWhenPlayerBehind':True,'interactions':[{'id':'inspect_mouth','kind':'inspect','rect':[36,12,1,1]}]},
 {'id':'w52_iron_ore','assetId':'resource_ore_iron_01','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[42,7,5,6],'collisionRect':[42,12,1,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_ore','kind':'inspect','rect':[41,11,3,3]}]},
 {'id':'w52_fence','assetId':'fence_plain_horizontal','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[8,22,1,1],'collisionRect':[8,22,1,1],'layer':'low_object','blocksMovement':True,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_fence','kind':'inspect','rect':[8,22,1,1]}]},
 {'id':'w52_door','assetId':'door_basic','state':'closed','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[14,20,1,3],'collisionRect':[14,22,1,1],'layer':'high_object','blocksMovement':True,'occludesPlayer':True,'fadeWhenPlayerBehind':True,'interactions':[{'id':'inspect_door','kind':'inspect','rect':[14,22,1,1]}]},
 {'id':'w52_stairs','assetId':'stairs_short_run_gray','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[20,18,1,5],'collisionRect':[20,22,0,0],'layer':'high_object','blocksMovement':False,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_stairs','kind':'inspect','rect':[20,22,1,1]}]},
 {'id':'w52_inn_sign','assetId':'sign_wall_inn','acceptanceLane':'w52_visual_closure','acceptanceStatus':'CANDIDATE','visualRect':[28,21,1,2],'collisionRect':[28,22,0,0],'layer':'high_object','blocksMovement':False,'occludesPlayer':False,'fadeWhenPlayerBehind':False,'interactions':[{'id':'inspect_sign','kind':'inspect','rect':[28,22,1,1]}]}
]
scene={'id':'world_visual_w52_acceptance_scene_v1','version':'1.0.0-w52','kind':'worldgen_scene','sceneId':'world_visual_w52_acceptance','title':'W52 World Visual Certification Acceptance','sceneKind':'exterior','biome':'temperate','role':'diagnostic_only','sceneSize':[W,H],'tileSize':32,'edgePolicy':'bounded','layers':{'terrain':terrain},'objects':objects,'transitions':[],'spawns':[{'id':'player_default','tile':[32,31]}],'editor':{'notes':['Visual closure board for newly resolved Tavern/cave/object identities plus typed W45 structures.','Well/scarecrow/bench/fallen-log/generic-standing-sign/greenhouse-marker are intentionally absent: they remain quarantined rather than substituted.']},'acceptance':{'pass':'167Z109W52','status':'CERTIFIED_WITH_EXPLICIT_QUARANTINES','visibleCandidateCount':len(objects),'quarantinedOptionalLegacyKinds':['well','scarecrow','bench','log','greenhouse_marker','sign']},'validationRules':['every visible object resolves through PublishedWorldAssetRegistry','no placeholder/rejected/missing visual appears on this board','quarantined optional legacy kinds remain omitted from production generation until exact source publication']}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(scene,indent=2)+'\n');print(f'WROTE {OUT.relative_to(ROOT)}')
